export type MovieType = {
  id: number;
  title: string;
  year: number;
  genre: string[];
  rating: number;
  director: string;
  actors: string[];
  plot: string;
  poster: string;
  trailer: string;
  runtime: number;
  awards: string;
  country: string;
  language: string;
  boxOffice: string;
  production: string;
  website: string;
};
export const MOVIES: MovieType[] = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    year: 1994,
    genre: ['Drama'],
    rating: 9.3,
    director: 'Frank Darabont',
    actors: ['Tim Robbins', 'Morgan Freeman'],
    plot: 'Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.',
    poster: 'https://fakeimg.pl/220x310/ff0000',
    trailer: 'https://example.com/shawshank_redemption_trailer.mp4',
    runtime: 142,
    awards: 'Nominated for 7 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$28.3 million',
    production: 'Columbia Pictures',
    website: 'http://www.warnerbros.com/movies/shawshank-redemption',
  },
  {
    id: 2,
    title: 'The Godfather',
    year: 1972,
    genre: ['Crime', 'Drama'],
    rating: 9.2,
    director: 'Francis Ford Coppola',
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    poster: 'https://fakeimg.pl/220x310/ffff00',
    trailer: 'https://example.com/the_godfather_trailer.mp4',
    runtime: 175,
    awards: 'Won 3 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$245.1 million',
    production: 'Paramount Pictures',
    website: 'https://www.paramountmovies.com/movies/the-godfather',
  },
  {
    id: 3,
    title: 'The Dark Knight',
    year: 2008,
    genre: ['Action', 'Crime', 'Drama'],
    rating: 9,
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Gary Oldman'],
    plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    poster: 'https://fakeimg.pl/220x310/ff00ff',
    trailer: 'https://example.com/the_dark_knight_trailer.mp4',
    runtime: 152,
    awards: 'Won 2 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$1.005 billion',
    production: 'Warner Bros. Pictures',
    website: 'https://www.warnerbros.com/movies/dark-knight',
  },
  {
    id: 4,
    title: 'Pulp Fiction',
    year: 1994,
    genre: ['Crime', 'Drama'],
    rating: 8.9,
    director: 'Quentin Tarantino',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    plot: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster: 'https://fakeimg.pl/220x310/0000ff',
    trailer: 'https://example.com/pulp_fiction_trailer.mp4',
    runtime: 154,
    awards: 'Won 1 Oscar',
    country: 'USA',
    language: 'English',
    boxOffice: '$213.9 million',
    production: 'Miramax Films',
    website: 'https://www.miramax.com/movie/pulp-fiction',
  },
  {
    id: 5,
    title: 'Forrest Gump',
    year: 1994,
    genre: ['Drama', 'Romance'],
    rating: 8.8,
    director: 'Robert Zemeckis',
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    plot: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.',
    poster: 'https://fakeimg.pl/220x310/ff00ff',
    trailer: 'https://example.com/forrest_gump_trailer.mp4',
    runtime: 142,
    awards: 'Won 6 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$677.9 million',
    production: 'Paramount Pictures',
    website: 'https://www.paramountmovies.com/movies/forrest-gump',
  },
  {
    id: 6,
    title: 'Inception',
    year: 2010,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    poster: 'https://fakeimg.pl/220x310/f8f8f8',
    trailer: 'https://example.com/inception_trailer.mp4',
    runtime: 148,
    awards: 'Won 4 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$829.9 million',
    production: 'Warner Bros. Pictures',
    website: 'https://www.warnerbros.com/movies/inception',
  },
  {
    id: 7,
    title: 'The Matrix',
    year: 1999,
    genre: ['Action', 'Sci-Fi'],
    rating: 8.7,
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    plot: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    poster: 'https://fakeimg.pl/220x310/f6f6f6',
    trailer: 'https://example.com/the_matrix_trailer.mp4',
    runtime: 136,
    awards: 'Won 4 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$463.5 million',
    production: 'Warner Bros. Pictures',
    website: 'https://www.warnerbros.com/movies/matrix',
  },
  {
    id: 8,
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    genre: ['Adventure', 'Drama', 'Fantasy'],
    rating: 8.9,
    director: 'Peter Jackson',
    actors: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    poster: 'https://fakeimg.pl/220x310/ff00ff',
    trailer: 'https://example.com/lotr_return_of_the_king_trailer.mp4',
    runtime: 201,
    awards: 'Won 11 Oscars',
    country: 'USA',
    language: 'English',
    boxOffice: '$1.142 billion',
    production: 'New Line Cinema',
    website: 'https://www.lordoftherings.net/film/the-return-of-the-king',
  },
];
